allowBuilds:
  '@rodrigo-barraza/service-library': true
  '@rodrigo-barraza/utilities-library': true
  sharp: true
  esbuild: true
  protobufjs: true
  canvas: true
  unrs-resolver: true
  '@rodrigo-barraza/service-library@https://codeload.github.com/rodrigo-barraza/service-library/tar.gz/257a5ba50eab4dd822b546946595b66490af0d75': true
  '@rodrigo-barraza/utilities-library@https://codeload.github.com/rodrigo-barraza/utilities-library/tar.gz/8ebb9ca5dbf6ae7eccd329c9fcfdded30b8b31d6': true
