import fs from 'fs';
import path from 'path';

const filePath = path.resolve('src/services/DiscordService.ts');
let content = fs.readFileSync(filePath, 'utf-8');

// Imports
if (!content.includes('import type { Message, Client, GuildMember, User, Presence, VoiceState, MessageReaction, PartialMessageReaction, PartialMessage, Interaction, ChatInputCommandInteraction, ButtonInteraction, Guild, TextChannel, GuildChannel, Collection as DiscordCollection } from "discord.js";')) {
  content = content.replace(
    'import type {',
    'import type { Message, Client, GuildMember, User, Presence, VoiceState, MessageReaction, PartialMessageReaction, PartialMessage, Interaction, ChatInputCommandInteraction, ButtonInteraction, Guild, TextChannel, GuildChannel, Collection as DiscordCollection } from "discord.js";\nimport type {'
  );
}

const patterns = [
  ['client: any', 'client: Client'],
  ['mongo: any', 'mongo: import("mongodb").MongoClient'],
  ['localMongo: any', 'localMongo: import("mongodb").MongoClient'],
  ['guild: any', 'guild: Guild'],
  ['message: any', 'message: Message'],
  ['oldMessage: any', 'oldMessage: Message | PartialMessage'],
  ['newMessage: any', 'newMessage: Message | PartialMessage'],
  ['member: any', 'member: GuildMember'],
  ['user: any', 'user: User'],
  ['reaction: any', 'reaction: MessageReaction | PartialMessageReaction'],
  ['oldState: any', 'oldState: VoiceState'],
  ['newState: any', 'newState: VoiceState'],
  ['oldPresence: any', 'oldPresence: Presence | null'],
  ['newPresence: any', 'newPresence: Presence'],
  ['oldMember: any', 'oldMember: GuildMember'],
  ['newMember: any', 'newMember: GuildMember'],
  ['interaction: any', 'interaction: Interaction'],
  ['queuedDatum: any', 'queuedDatum: Record<string, unknown>'],
  ['type: any = "EMOJI"', 'type: string = "EMOJI"'],
  ['maxRetries: any = 3', 'maxRetries: number = 3'],
  ['(error as any)', '(error as Error & { data?: { retry_after?: number, opcode?: number } })'],
  ['new Promise((resolve: any)', 'new Promise((resolve: (value: void | PromiseLike<void>) => void)'],
  ['(arg: any)', '(arg: string)'],
  ['const queuedData: any[] = [];', 'const queuedData: Record<string, unknown>[] = [];'],
  ['messageId: any', 'messageId: string'],
  ['userId: any', 'userId: string'],
  ['}: any', '}: Record<string, unknown>'],
  ['source: any', 'source: Record<string, unknown> | null | undefined'],
  ['emoji: any', 'emoji: string'],
  ['(part: any)', '(part: string)'],
  ['const emojiUrls: any[] = [];', 'const emojiUrls: string[] = [];'],
  ['systemPrompt: any, // should stay the same', 'systemPrompt: string, // should stay the same'],
  ['message: any, // should stay the same', 'message: Message, // should stay the same'],
  ['participant: any, //is either user or member', 'participant: User | GuildMember, //is either user or member'],
  ['who: any,', 'who: "MENTIONED" | "SECONDARY" | string,'],
  ['participantIndex: any,', 'participantIndex: number,'],
  ['messages: any, // should stay the same', 'messages: Message[], // should stay the same'],
  ['participantsAvatarsCollection: any,', 'participantsAvatarsCollection: DiscordCollection<string, string | null>,'],
  ['participantsBannersCollection: any,', 'participantsBannersCollection: DiscordCollection<string, string | null>,'],
  ['conversation: any,', 'conversation: Record<string, unknown>[],'],
  ['captionsMap: any,', 'captionsMap: Map<string, string>,'],
  ['let messageSentAt: any;', 'let messageSentAt: string | null = null;'],
  ['let messageSentAtRelative: any;', 'let messageSentAtRelative: string | null = null;'],
  ['(message: any) => message.author.id', '(message: Message) => message.author.id'],
  ['(a: any) => a.type', '(a: import("discord.js").Activity) => a.type'],
  ['toHex = (d: any)', 'toHex = (d: number)'],
  ['(perm: any)', '(perm: bigint)'],
  ['(role: any)', '(role: import("discord.js").Role)'],
  ['let generatedText: any;', 'let generatedText: string | null = null;'],
  ['const serverContext: any[] = [];', 'const serverContext: string[] = [];'],
  ['let image: any;', 'let image: string | null = null;'],
  ['(context: any)', '(context: string)'],
  ['(keyword: any)', '(keyword: string)'],
  ['(pattern: any)', '(pattern: RegExp)'],
  ['(channel: any) => channel.type', '(channel: GuildChannel) => channel.type'],
  ['(channel.members as any)', 'channel.members'],
  ['let participantMember: any;', 'let participantMember: GuildMember | undefined;'],
  ['let participantUser: any;', 'let participantUser: User | undefined;'],
  ['let participantConversation: any;', 'let participantConversation: Record<string, unknown>[] | undefined;'],
  ['const allVisionUrls: any[] = [];', 'const allVisionUrls: string[] = [];'],
  ['(a: any)', '(a: import("discord.js").Attachment)'],
  ['const knownParticipants: any[] = [];', 'const knownParticipants: string[] = [];'],
  ['const matchedIds: any[] = [];', 'const matchedIds: string[] = [];'],
  ['(n: any) => n && n.length', '(n: string) => n && n.length'],
  ['(n: any) => n.toLowerCase()', '(n: string) => n.toLowerCase()'],
  ['.sort((a: any, b: any) => b[1] - a[1])', '.sort((a: [string, number], b: [string, number]) => b[1] - a[1])'],
  ['.map(([id]: any) => id)', '.map(([id]: [string, number]) => id)'],
  ['(member: any) => member.id !==', '(member: GuildMember) => member.id !=='],
  ['(filteredMemberMentions as any)', 'filteredMemberMentions'],
  ['(participant: any)', '(participant: GuildMember | User)'],
  ['const participantUserIds: any[] = [];', 'const participantUserIds: string[] = [];'],
  ['(m: any) => m.role === "user"', '(m: Record<string, unknown>) => m.role === "user"'],
  ['(m: any) => {', '(m: Record<string, unknown>) => {'],
  ['(m: any) => m[1]', '(m: RegExpMatchArray) => m[1]'],
  ['(t: any) => t.length > 0', '(t: string) => t.length > 0'],
  ['const imageUrls: any[] = [];', 'const imageUrls: string[] = [];'],
  ['const imageLabels: any[] = [];', 'const imageLabels: string[] = [];'],
  ['const mentionsImageUrls: any[] = [];', 'const mentionsImageUrls: Record<string, unknown>[] = [];'],
  ['(value: any, key: any)', '(value: string, key: string)'],
  ['(attachment: any)', '(attachment: import("discord.js").Attachment)'],
  ['(member: any)', '(member: GuildMember)'],
  ['(user: any)', '(user: User)'],
  ['(m: any) => m.userId === matchedId', '(m: Record<string, unknown>) => m.userId === matchedId'],
  ['(m: any) => !avatarUserIdsAdded', '(m: Record<string, unknown>) => !avatarUserIdsAdded'],
  ['(emojisInMessage as any)', 'emojisInMessage'],
  ['(label: any, i: any)', '(label: string, i: number)'],
  ['let combinedGuildInformation: any;', 'let combinedGuildInformation: string | null = null;'],
  ['let combinedChannelInformation: any;', 'let combinedChannelInformation: string | null = null;'],
  ['let generatedTextResponse: any;', 'let generatedTextResponse: string | null = null;'],
  ['let generatedImage: any;', 'let generatedImage: string | null = null;'],
  ['const memoryParticipants: any[] = [];', 'const memoryParticipants: GuildMember[] = [];'],
  ['(participantsCollection as any)', 'participantsCollection'],
  ['(memberMentionsCollection as any)', 'memberMentionsCollection'],
  ['(p: any)', '(p: GuildMember)'],
  ['(result: any)', '(result: string)'],
  ['(error: any)', '(error: Error)'],
  ['recentMessage: any', 'recentMessage: Message'],
  ['const conversation: any[] = [];', 'const conversation: Record<string, unknown>[] = [];'],
  ['conversations: [] as any[],', 'conversations: [] as Promise<unknown>[],'],
  ['emojis: [] as any[],', 'emojis: [] as Promise<unknown>[],'],
  ['audio: [] as any[],', 'audio: [] as Promise<unknown>[],'],
  ['images: [] as any[],', 'images: [] as Promise<unknown>[],'],
  ['replies: [] as any[],', 'replies: [] as Promise<unknown>[],'],
  ['const messageProcessingData: any[] = [];', 'const messageProcessingData: Record<string, unknown>[] = [];'],
  ['let currentSequenceMessages: any[] = [];', 'let currentSequenceMessages: Message[] = [];'],
  ['const userExists: any =', 'const userExists: User | undefined ='],
  ['let avatarUrl: any, bannerUrl: any;', 'let avatarUrl: string | null = null, bannerUrl: string | null = null;'],
  ['(item: any)', '(item: { promise: Promise<unknown> })'],
  ['let imageDescription: any, imageSize: any, imageWidth: any, imageHeight: any;', 'let imageDescription: string | null = null, imageSize: number = 0, imageWidth: number = 0, imageHeight: number = 0;'],
  ['let attachmentContext: any;', 'let attachmentContext: string | null = null;'],
  ['(a: any, b: any) => a.rawPosition', '(a: import("discord.js").Role, b: import("discord.js").Role) => a.rawPosition'],
  ['title: any', 'title: string'],
  ['description: any', 'description: string'],
  ['sourceArray: any', 'sourceArray: { id: string, emojiId?: string }[]'],
  ['options: Record<string, any>', 'options: Record<string, unknown>'],
  ['(src: any)', '(src: { id: string })'],
  ['(a: any, b: any) => a.name.localeCompare', '(a: import("discord.js").Role, b: import("discord.js").Role) => a.name.localeCompare'],
  ['const rows: any[] = [];', 'const rows: import("discord.js").ActionRowBuilder<import("discord.js").StringSelectMenuBuilder>[] = [];'],
  ['(messages: any)', '(messages: DiscordCollection<string, Message>)'],
  ['{ mongo }: any', '{ mongo }: { mongo: import("mongodb").MongoClient }'],
  ['{ localMongo }: any', '{ localMongo }: { localMongo: import("mongodb").MongoClient }'],
  ['{ localMongo, channelIds, guildIds, dateLimit }: any', '{ localMongo, channelIds, guildIds, dateLimit }: { localMongo: import("mongodb").MongoClient, channelIds?: string[], guildIds?: string[], dateLimit?: string }'],
  ['actionType: any', 'actionType: string'],
  ['(att: any)', '(att: import("discord.js").Attachment)'],
  ['(sticker: any)', '(sticker: import("discord.js").Sticker)'],
  ['(q: any)', '(q: Record<string, unknown>)'],
  ['{ _mongo, localMongo }: any', '{ _mongo, localMongo }: { _mongo: import("mongodb").MongoClient, localMongo: import("mongodb").MongoClient }'],
  ['(YouTubeService as any)', '(YouTubeService as Record<string, (...args: unknown[]) => void>)'],
  ['messagesTranscriptionsCollection: any', 'messagesTranscriptionsCollection: DiscordCollection<string, string>'],
  ['messagesImagesCollection: any', 'messagesImagesCollection: DiscordCollection<string, string>'],
  ['userMessage: any', 'userMessage: Message'],
  ['modifiedContent: any', 'modifiedContent: string'],
  ['const messageImageUrls: any[] = [];', 'const messageImageUrls: string[] = [];'],
  ['_isReply: any = false', '_isReply: boolean = false'],
  ['undefined as any', 'undefined as never'],
  ['(DiscordUtilityService as any)', '(DiscordUtilityService as Record<string, (...args: unknown[]) => void>)'],
  ['(luposClient as any)', '(luposClient as Client & { commands: DiscordCollection<string, unknown> })'],
  ['(file: any)', '(file: string)'],
  ['{ channelIds, guildIds, dateLimit }: any = {}', '{ channelIds, guildIds, dateLimit }: { channelIds?: string[], guildIds?: string[], dateLimit?: string } = {}']
];

for (const [search, replace] of patterns) {
  content = content.split(search).join(replace);
}

fs.writeFileSync(filePath, content, 'utf-8');
console.log('Fixed DiscordService.ts Part 1');
